version: "3.9"

services:
  db:
    image: mariadb:10.4
    container_name: damncrud_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: damncrud
    volumes:
      - ./damncrud.sql:/docker-entrypoint-initdb.d/damncrud.sql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: damncrud_app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
    networks:
      - testnet

networks:
  testnet: