name: Selenium CI (End to End)

on:
  push:
    branches: [ main ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome and matching ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable  # atau 'latest' atau versi spesifik misal '131'

    - name: Verify Chrome & ChromeDriver versions
      run: |
        google-chrome --version
        chromedriver --version

    - name: Start Docker
      run: docker compose up -d --build

    - name: Wait for application to be healthy
      run: |
        python -c "from conftest import wait_for_app; wait_for_app('http://localhost:8080')"


    - name: Wait for DB
      run: |
        sleep 20  

    - name: Run Tests
      run: pytest -n auto -v

    - name: Stop Docker
      if: always()
      run: docker compose down -v